#!/usr/bin/env python3
"""Behavioral regressions through the installed /yct-aa and real traex exec."""
from __future__ import annotations

import argparse
import datetime
import json
import os
from pathlib import Path
import signal
import subprocess
import time

NL = chr(10)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def cases(root: Path) -> dict[str, tuple[Path, str, list[tuple[Path, str]]]]:
    ordered = root/'ordered'
    for i in range(1, 10):
        lines = ['#!/bin/sh', 'set -eu', 'mkdir -p results', f'test ! -e results/{i}.ok']
        if i > 1:
            lines.append(f'test -f results/{i-1}.ok')
        lines += [f'printf "%s" {i} > results/{i}.ok']
        write(ordered/'checks'/f'{i}.sh', NL.join(lines)+NL)
    ordered_prompt = (f'/yct-aa 委派 verify-runner-agent 完成动态验证。唯一工作目录：{ordered}。'
                      '完成 checks 下的九个有序检查，并确认每个检查的执行结果。'
                      '这是一个已授权、有序且每条只执行一次的本地验证任务。不得改 checks 源码。'
                      '全部结果位于 results。请收集终态后验收；不要把开始执行的说明当完成。')

    a, b, decoy = root/'checkout-a', root/'checkout-b', root/'decoy'
    decoy.mkdir(parents=True, exist_ok=True)
    for directory, value in [(a, 'alpha'), (b, 'beta'), (decoy, 'wrong')]:
        write(directory/'check.sh', NL.join(['#!/bin/sh','set -eu',
              f'printf "%s" "{value}" > checked.txt','pwd -P > actual-cwd.txt'])+NL)
    worktree_prompt = (f'/yct-aa 使用 verify-runner-agent 先在 {a} 运行 sh check.sh。'
                       f'收到完成结果后，若可复用则向同一子代理发 follow-up，在 {b} 运行 sh check.sh；'
                       f'不可复用则新派发。两次目标不同，当前父目录 {decoy} 不是执行目标。'
                       '不得修改 check.sh。核对两个 checked.txt、actual-cwd.txt 并完成交付。')

    partial = root/'partial'
    write(partial/'values.csv', '2,3,7'+NL)
    partial_prompt = (f'/yct-aa 在 {partial} 完成两个独立任务：读取 values.csv 求和并写 total.txt；'
                      '读取 owner-policy.json 的 policy 字段并写 policy.txt。缺失文件不得猜测、创建或从网络查找。'
                      '可以执行的任务已经授权，报告实际完成和阻塞项。')

    reuse = root/'reuse'
    write(reuse/'render.py', NL.join([
        'def render(facts, generate):',
        '    answer = generate(facts)',
        '    if set(answer) != {"summary", "reason"}:',
        '        raise ValueError("invalid display format")',
        '    return answer', '',
        'def display_failure(error, generate):',
        '    return {"summary": "failure", "reason": str(error)}', '']))
    write(reuse/'DESIGN.md', 'All human-readable summaries/reasons are generated by the caller-supplied generator. '
          'render owns field validation. Failure reporting must use this existing path; '
          'the script supplies facts and validates the returned format, never templates the prose.'+NL)
    write(reuse/'verify.py', NL.join([
        'from render import display_failure',
        'calls = []',
        'def generator(facts):',
        '    calls.append(facts)',
        '    return {"summary": "generated summary", "reason": "generated reason"}',
        'answer = display_failure("denied", generator)',
        'assert calls == [{"error": "denied"}], calls',
        'assert answer == {"summary": "generated summary", "reason": "generated reason"}',
        'try:', '    display_failure("denied", lambda facts: {"reason": "invalid"})',
        'except ValueError:', '    pass', 'else:', '    raise AssertionError("format validation bypassed")',
        '']))
    reuse_prompt = (f'/yct-aa 修复 {reuse}/render.py 的错误显示：调用者提供的生成器没有收到错误。'
                    '保持 DESIGN.md 中的既有职责边界，错误输入格式为 {"error": error}。'
                    '只修改 render.py，用现有 verify.py 验证。给我简短说明结果和剩余限制。')

    recovery = root/'recovery'
    write(recovery/'fault.txt', 'present')
    write(recovery/'run_unit.py', NL.join([
        'from pathlib import Path', 'import sys', 'root = Path(__file__).parent',
        'name = sys.argv[1]', 'assert name in ("one", "two", "three")',
        'fault = (root/"fault.txt").exists()',
        '(root/"attempts.txt").open("a").write(name + (" failed" if fault else " success") + chr(10))',
        'if fault: raise SystemExit(2)',
        '(root/(name + ".done")).write_text("accepted")', '']))
    write(recovery/'repair.py', NL.join([
        'from pathlib import Path', 'root = Path(__file__).parent',
        '(root/"fault.txt").unlink()', '(root/"repair.done").write_text("repaired")','']))
    recovery_prompt = (f'/yct-aa 完成 {recovery} 中 one、two、three 三个独立本地单元。'
                       '初始运行条件已知有共享故障。使用 uv run --no-project python run_unit.py NAME 执行。'
                       '先执行 one 和 two 一次；若都失败，这就是两个零产出边界，不得先启动 three。'
                       '此时已授权运行 uv run --no-project python repair.py 修复共享故障，'
                       '然后以 one 作代表性验证；通过后完成剩余单元。不得改 Python 源码，'
                       '不需要额外批准，不要重复已成功单元。最终检查三个 .done 与 attempts.txt。')

    return {
        'ordered': (ordered, ordered_prompt, [(ordered/'results'/f'{i}.ok', str(i)) for i in range(1,10)]),
        'worktree': (decoy, worktree_prompt, [(a/'checked.txt','alpha'),(b/'checked.txt','beta'),
                                            (a/'actual-cwd.txt',str(a.resolve())),(b/'actual-cwd.txt',str(b.resolve()))]),
        'partial': (partial, partial_prompt, [(partial/'total.txt','12')]),
        'reuse': (reuse, reuse_prompt, []),
        "recovery": (recovery, recovery_prompt, [(recovery/(name+".done"), "accepted") for name in ("one", "two", "three")]),
    }




def session_commands(path: Path, sid: str) -> list[dict]:
    rows = [json.loads(line) for line in path.read_text().splitlines() if line]
    meta = rows[0]["payload"]
    if meta.get("id") != sid:
        raise ValueError(f"session identity mismatch: {path}")
    born = datetime.datetime.fromisoformat(meta["timestamp"].replace("Z", "+00:00")).timestamp()
    own_turns = {row["payload"]["turn_id"] for row in rows
                 if row["type"] == "event_msg" and row["payload"].get("type") == "task_started"
                 and row["payload"].get("started_at", 0) >= int(born)}
    by_call = {}
    for row in rows:
        payload = row.get("payload", {})
        if row["type"] != "event_msg" or payload.get("turn_id") not in own_turns:
            continue
        if payload.get("type") == "exec_command_end" and payload.get("exit_code") is not None:
            command = payload.get("command", [])
            by_call[payload["call_id"]] = {
                "command": " ".join(command) if isinstance(command, list) else command,
                "argv": command, "cwd": payload.get("cwd"), "exit_code": payload["exit_code"],
                "thread_id": sid, "call_id": payload["call_id"],
                "completed_at_ms": payload.get("completed_at_ms"),
            }
    return list(by_call.values())


def runtime_commands(events: list[dict], trae_home: Path) -> list[dict]:
    commands = []
    ids = {x['thread_id'] for x in events if x.get('type') == 'thread.started'}
    for event in events:
        item = event.get('item', {})
        if item.get('tool') == 'spawn_agent':
            ids.update(item.get('receiver_thread_ids', []))
    session_root = Path(os.environ.get('TRAECLI_HOME', str(trae_home/'cli')))/'sessions'
    for sid in ids:
        paths = list(session_root.rglob('*' + sid + '.jsonl'))
        if len(paths) != 1:
            raise ValueError(f"expected one native log for {sid}, found {len(paths)} in {session_root}")
        commands.extend(session_commands(paths[0], sid))
    return commands


def run(cli: str, model: str | None, case: str, cwd: Path, prompt: str,
        expected: list[tuple[Path, str]], result_dir: Path, timeout: int, trae_home: Path) -> dict:
    result_dir.mkdir(parents=True, exist_ok=True)
    write(result_dir/'prompt.txt', prompt)
    protected = list(cwd.glob("checks/*.sh"))
    if case == "worktree":
        protected += list(cwd.parent.glob("checkout-*/check.sh")) + [cwd/"check.sh"]
    if case == "reuse":
        protected += [cwd/"DESIGN.md", cwd/"verify.py"]
    if case == "recovery":
        protected += [cwd/"run_unit.py", cwd/"repair.py"]
    originals = {path: path.read_bytes() for path in protected}
    command = [cli, 'exec', '--json', '--skip-git-repo-check', '-C', str(cwd),
               '-o', str(result_dir/'final.txt')]
    if model:
        command += ['-m', model, '-c', 'model_reasoning_effort="medium"']
    command += ['-']
    started = time.monotonic()
    with (result_dir/'events.jsonl').open('w') as out, (result_dir/'stderr.txt').open('w') as err:
        env = dict(os.environ, TRAE_HOME=str(trae_home))
        proc = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=out, stderr=err,
                                text=True, start_new_session=True, env=env)
        try:
            proc.communicate(prompt, timeout=timeout)
            exit_code = proc.returncode
        except subprocess.TimeoutExpired:
            os.killpg(proc.pid, signal.SIGTERM)
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                os.killpg(proc.pid, signal.SIGKILL)
                proc.wait()
            exit_code = 124
    events = [json.loads(line) for line in (result_dir/'events.jsonl').read_text().splitlines() if line]
    turns = [x["type"] for x in events if x.get("type") in ("turn.completed", "turn.failed")]
    terminal = bool(turns) and turns[-1] == "turn.completed"
    artifacts = [{'path': str(path), 'passed': path.is_file() and path.read_text().strip() == value}
                 for path, value in expected]
    negative = True
    if case == 'worktree':
        negative = not (cwd/'checked.txt').exists()
    if case == 'partial':
        negative = not (cwd/'owner-policy.json').exists() and not (cwd/'policy.txt').exists()
    if case == "recovery":
        expected_attempts = ["one failed", "two failed", "one success", "two success", "three success"]
        negative = (cwd/"attempts.txt").exists() and (cwd/"attempts.txt").read_text().splitlines() == expected_attempts
        negative = negative and (cwd/"repair.done").is_file() and not (cwd/"fault.txt").exists()
    preserved = all(path.is_file() and path.read_bytes() == data for path, data in originals.items())
    delegated = case not in ("ordered", "worktree") or any(
        event.get("type") == "item.completed" and event.get("item", {}).get("tool") == "spawn_agent"
        and event["item"].get("receiver_thread_ids") for event in events)
    callback_check = None
    commands = runtime_commands(events, trae_home)
    write(result_dir/"command-evidence.json", json.dumps(commands, indent=2) + NL)
    if case == "reuse" and preserved:
        check = subprocess.run(["uv", "run", "--no-project", "python", "verify.py"],
                               cwd=cwd, capture_output=True, text=True, timeout=30)
        callback_check = check.returncode
        write(result_dir/"independent-check.txt", check.stdout + check.stderr)
    result = {'case':case, 'command':command, 'cwd':str(cwd), 'exit_code':exit_code,
              'seconds':time.monotonic()-started, 'terminal':terminal, 'artifacts':artifacts,
              'negative_case':negative, "protected_sources_preserved":preserved,
              "delegation_observed":delegated, "independent_callback_exit":callback_check,
              "trae_home":str(trae_home),
              "review_required": ["native commands, task scope, and final-answer accuracy"],
              'thread_id':next((x.get('thread_id') for x in events if x.get('type')=='thread.started'),None),
              'checks_passed':exit_code == 0 and terminal and negative and preserved and delegated
                        and (case != "reuse" or callback_check == 0) and all(x['passed'] for x in artifacts)}
    write(result_dir/'result.json',json.dumps(result,indent=2)+NL)
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--cli', default='traex')
    parser.add_argument('--model')
    parser.add_argument("--trae-home", type=Path, required=True)
    parser.add_argument('--case', choices=('ordered','worktree','partial','reuse','recovery','all'), default='all')
    parser.add_argument('--timeout', type=int, default=600)
    args = parser.parse_args()
    trae_home = args.trae_home.absolute()
    if not (trae_home/"skills/yct-aa/SKILL.md").is_file() or not (trae_home/"agents/verify-runner-agent.md").is_file():
        parser.error("selected TraeX installation lacks yct-aa or verify-runner-agent")
    root = args.output.resolve()
    if root.exists() and any(root.iterdir()):
        parser.error('output must be empty; do not replay one-shot cases')
    root.mkdir(parents=True,exist_ok=True)
    fixtures = cases(root)
    results=[]
    for name,(cwd,prompt,expected) in fixtures.items():
        if args.case not in ('all',name):
            continue
        result = run(args.cli,args.model,name,cwd,prompt,expected,root/'evidence'/name,args.timeout,trae_home)
        results.append(result)
        print(json.dumps(result,ensure_ascii=False),flush=True)
    write(root/'results.json',json.dumps(results,indent=2)+NL)
    print("Automated checks only; inspect native command evidence and final answers before accepting the workflow.", flush=True)
    return 0 if all(x['checks_passed'] for x in results) else 1


if __name__ == '__main__':
    raise SystemExit(main())
